// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using monitoring_management.Models;

#nullable disable

namespace monitoring_management.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("monitoring_management.Models.AcademicProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CollegeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("academic_programs", (string)null);
                });

            modelBuilder.Entity("monitoring_management.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("AdminId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("admin", (string)null);
                });

            modelBuilder.Entity("monitoring_management.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("category_name");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("monitoring_management.Models.ResearchMember", b =>
                {
                    b.Property<string>("MemberId")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("member_id");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("member_name");

                    b.Property<string>("PaperId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("paper_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("role");

                    b.Property<string>("StudentId")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("student_id");

                    b.HasKey("MemberId");

                    b.HasIndex("PaperId");

                    b.HasIndex("StudentId");

                    b.ToTable("research_members", (string)null);
                });

            modelBuilder.Entity("monitoring_management.Models.ResearchPaper", b =>
                {
                    b.Property<string>("PaperId")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("paper_id");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_uploaded");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("FilePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_path");

                    b.Property<string>("Keywords")
                        .HasColumnType("longtext")
                        .HasColumnName("keywords");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("uploaded_by");

                    b.Property<short>("Year")
                        .HasColumnType("year")
                        .HasColumnName("year");

                    b.HasKey("PaperId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("research_papers", (string)null);
                });

            modelBuilder.Entity("monitoring_management.Models.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("program");

                    b.Property<string>("StudentNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("student_no");

                    b.HasKey("StudentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("StudentNo")
                        .IsUnique();

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("monitoring_management.Models.ResearchMember", b =>
                {
                    b.HasOne("monitoring_management.Models.ResearchPaper", "ResearchPaper")
                        .WithMany("ResearchMembers")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("monitoring_management.Models.Student", "Student")
                        .WithMany("ResearchMembers")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ResearchPaper");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("monitoring_management.Models.ResearchPaper", b =>
                {
                    b.HasOne("monitoring_management.Models.Category", "Category")
                        .WithMany("ResearchPapers")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("monitoring_management.Models.Student", "Student")
                        .WithMany("ResearchPapers")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("monitoring_management.Models.Category", b =>
                {
                    b.Navigation("ResearchPapers");
                });

            modelBuilder.Entity("monitoring_management.Models.ResearchPaper", b =>
                {
                    b.Navigation("ResearchMembers");
                });

            modelBuilder.Entity("monitoring_management.Models.Student", b =>
                {
                    b.Navigation("ResearchMembers");

                    b.Navigation("ResearchPapers");
                });
#pragma warning restore 612, 618
        }
    }
}
