using System.ComponentModel.DataAnnotations;

namespace monitoring_management.Models;

public class SubmitResearchViewModel
{
    [Required(ErrorMessage = "Title is required.")]
    [MaxLength(255)]
    public string Title { get; set; } = string.Empty;

    [Required(ErrorMessage = "Description is required.")]
    public string Description { get; set; } = string.Empty;

    [Required(ErrorMessage = "Please select a category.")]
    public int? CategoryId { get; set; }

    [Required(ErrorMessage = "Please select an academic year.")]
    public int? Year { get; set; }

    public string? Keywords { get; set; }

    public string Status { get; set; } = "Pending";

    // Binds the hidden inputs generated by the member-search JS:
    // Members[0].StudentId, Members[0].MemberName, Members[1].StudentId, ...
    public List<MemberEntry> Members { get; set; } = new();
}

public class MemberEntry
{
    public string? StudentId { get; set; }

    [Required]
    public string MemberName { get; set; } = string.Empty;
}